
server:
  port: 8094

spring:
  application:
    name: UniversityMannagementSystem

  oracle:
    datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: SYSTEM
      password: omjee123
      driver-class-name: oracle.jdbc.OracleDriver

  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 31082002
      driver-class-name: com.mysql.cj.jdbc.Driver

  security:
      user:
        name: om
        password: omjee123