server:
  port: 8099

spring:
  application:
    name: SpringSecurity
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 31082002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true